# Generated by Django 4.1.6 on 2023-03-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('emailID', models.EmailField(max_length=254)),
                ('linkedIN', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('phoneNO', models.BigIntegerField()),
                ('about', models.CharField(max_length=100)),
            ],
        ),
    ]
