# Generated by Django 4.1.6 on 2023-03-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerc',
            name='about',
            field=models.TextField(max_length=100),
        ),
    ]
