# Generated by Django 4.1.6 on 2023-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_peerc_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerc',
            name='profileP',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
