# Generated by Django 4.1.6 on 2023-03-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_peerc_profilep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerc',
            name='profileP',
            field=models.ImageField(default='default.jpg', upload_to='./dashboard/profile_pics'),
        ),
    ]
